# Scientific Programming in Python - Dictionaries and Functions

### Problem 1. Library, with dictionaries

We’ll revisit the Problem 3 of Assignment 2, where we had to manipulate some data from a fake
library.

In this problem, we had the following format for the data:


In [40]:
[[123456,312314,531337],                     # Student IDS
 ['John Doe',' Jane Miller','Ted Johnson'],  # Student Names
 [1.49,0.00,8.12]]                           # Amounts owed

[[123456, 312314, 531337],
 ['John Doe', ' Jane Miller', 'Ted Johnson'],
 [1.49, 0.0, 8.12]]

>**(a)** Construct a dictionary to store this data, using the student ID (the ﬁrst big number) as the **key**, and the amount owed as the **values**. 

> Use the code below to get you started. You can type the key, value pairs into the curly brackets `{ }`.

In [41]:
student_id_to_amount_owed = {123456: 1.49, 312314: 0.0, 531337: 8.12, 273263: 0.0, 102931: 1.2, 391273: 10.39}
print(student_id_to_amount_owed)

{123456: 1.49, 312314: 0.0, 531337: 8.12, 273263: 0.0, 102931: 1.2, 391273: 10.39}


In [42]:
student_id_to_amount_owed = {}  # complete this line to include all the student IDs and amounts owed

library = []
path = "library_data.txt"
with open(path, "r") as lib:
    for line in lib:
        library.append(line)

for text in library:
    splited = text.split(" ")
    student_id_to_amount_owed[int(splited[0])] = float(splited[3])
print(student_id_to_amount_owed)

{123456: 1.49, 312314: 0.0, 531337: 8.12, 273263: 0.0, 102931: 1.2, 391273: 10.39}


> **(b)** Use this dictionary to find out how much money the student with id `531337` owes. 

> You should use square brackets `[ ]` to index into your dictionary.


In [43]:
amount_owed_by_531337 = student_id_to_amount_owed[531337] # type answer here
print(amount_owed_by_531337)

8.12


> Try also finding out how much 123456 owes. What about newly enrolled student 999888?

In [44]:
student_id_to_amount_owed[123456]

1.49

In [45]:
student_id_to_amount_owed[999888]

KeyError: 999888

999888 학생의 경우, 아직 데이터가 없어 알 수 없다.

> **(c)** Create another dictionary which maps the name of the student to its student id.  This time, instead of typing the values in by hand, fill in this dictionary by looping over the list `student_names_and_ids` given below:


In [46]:
student_names_and_ids = [('John Doe', 123456), ('Jane Miller', 312314), ('Ted Johnson', 531337)]

studentname_to_id = {}  # initialise empty dictionary

# write code here to populate the dictionary
for a, b in student_names_and_ids:
    studentname_to_id[a] = b

print(studentname_to_id)
# desired output : {'Jane Miller': 312314, 'John Doe': 123456, 'Ted Johnson': 531337}

{'John Doe': 123456, 'Jane Miller': 312314, 'Ted Johnson': 531337}



> **(c)** Print how much money 'John Doe' owes the library, using both of your dictionaries. 

>  *(Hint: First find out John Doe's student ID, then use this to find out how much he owes)*

In [47]:
John_doe_balance = student_id_to_amount_owed[studentname_to_id['John Doe']]
print(John_doe_balance)

1.49


> **(d)** Create the list of the names of students owing more than £1.0 to the library.

> *(Hint: If it is easier, first make a list of all the student IDs which owe more than £1.0 Then adapt the code to create a list of names instead).*


In [48]:
bad_students = [] # type answer here
for key in studentname_to_id:
    if student_id_to_amount_owed[studentname_to_id[key]] >= 1.0:
        bad_students.append(key)
        
print(bad_students)

['John Doe', 'Ted Johnson']


### Problem 2. Counting words

>**(a)** In this problem we’ll use the text of Alice in Wonderland to construct dictionaries counting the
number of times particular words and pairs of words appear.

In [49]:
import urllib.request
URL = "http://ucl-cs-grad.github.io/scipython/notebooks/day2/alice.txt"
f = urllib.request.urlopen(URL)
open("alice.txt","wb").write(f.read())

167546

This will create a new file called "alice.txt"

>**(b)** We'll process alice.txt in loops like this:

>Modify this code so that it creates a new dictionary called words at (1).<br> For (2), if a word
is not already in the dictionary words, then add it to the dictionary with a value of 1. <br>If a
word is already in the dictionary words, then increment the value stored in the dictionary
by one.<br>

>At location (3), print out the dictionary words.

In [50]:
f = open("alice.txt", "r")
# your code here (1)
alice_word = {}
for line in f.readlines():
    for word in line.strip().split():
        # your code here (2)
        if word in alice_word.keys():
            alice_word[word] += 1
        else:
            alice_word[word] = 1
            
# your code here (3)
print(alice_word.keys())

dict_keys(['Project', "Gutenberg's", "Alice's", 'Adventures', 'in', 'Wonderland,', 'by', 'Lewis', 'Carroll', 'This', 'eBook', 'is', 'for', 'the', 'use', 'of', 'anyone', 'anywhere', 'at', 'no', 'cost', 'and', 'with', 'almost', 'restrictions', 'whatsoever.', 'You', 'may', 'copy', 'it,', 'give', 'it', 'away', 'or', 're-use', 'under', 'terms', 'Gutenberg', 'License', 'included', 'this', 'online', 'www.gutenberg.org', 'Title:', 'Wonderland', 'Author:', 'Posting', 'Date:', 'June', '25,', '2008', '[EBook', '#11]', 'Release', 'March,', '1994', '[Last', 'updated:', 'December', '20,', '2011]', 'Language:', 'English', 'Character', 'set', 'encoding:', 'ASCII', '***', 'START', 'OF', 'THIS', 'PROJECT', 'GUTENBERG', 'EBOOK', "ALICE'S", 'ADVENTURES', 'IN', 'WONDERLAND', 'THE', 'MILLENNIUM', 'FULCRUM', 'EDITION', '3.0', 'CHAPTER', 'I.', 'Down', 'Rabbit-Hole', 'Alice', 'was', 'beginning', 'to', 'get', 'very', 'tired', 'sitting', 'her', 'sister', 'on', 'bank,', 'having', 'nothing', 'do:', 'once', 'twice'

더 정확한 결과를 위해 특수문자를 제거하고, 책의 시작 부분부터 실행해보자.

In [51]:
import re

with open("alice.txt") as f:
    lines = f.readlines()[40:]
lines = "".join(lines)
preprocessed = re.sub('[^A-Za-z]', ' ', lines)   
    
print(preprocessed[:1000])

CHAPTER I  Down the Rabbit Hole  Alice was beginning to get very tired of sitting by her sister on the bank  and of having nothing to do  once or twice she had peeped into the book her sister was reading  but it had no pictures or conversations in it   and what is the use of a book   thought Alice  without pictures or conversations    So she was considering in her own mind  as well as she could  for the hot day made her feel very sleepy and stupid   whether the pleasure of making a daisy chain would be worth the trouble of getting up and picking the daisies  when suddenly a White Rabbit with pink eyes ran close by her   There was nothing so VERY remarkable in that  nor did Alice think it so VERY much out of the way to hear the Rabbit say to itself   Oh dear  Oh dear  I shall be late    when she thought it over afterwards  it occurred to her that she ought to have wondered at this  but at the time it all seemed quite natural   but when the Rabbit actually TOOK A WATCH OUT OF ITS WAISTCO

In [52]:
alice_word = {}
for line in preprocessed.split("\n"):
    for word in line.strip().split():
        if word in alice_word.keys():
            alice_word[word] += 1
        else:
            alice_word[word] = 1
            

print(alice_word.keys())

dict_keys(['CHAPTER', 'I', 'Down', 'the', 'Rabbit', 'Hole', 'Alice', 'was', 'beginning', 'to', 'get', 'very', 'tired', 'of', 'sitting', 'by', 'her', 'sister', 'on', 'bank', 'and', 'having', 'nothing', 'do', 'once', 'or', 'twice', 'she', 'had', 'peeped', 'into', 'book', 'reading', 'but', 'it', 'no', 'pictures', 'conversations', 'in', 'what', 'is', 'use', 'a', 'thought', 'without', 'So', 'considering', 'own', 'mind', 'as', 'well', 'could', 'for', 'hot', 'day', 'made', 'feel', 'sleepy', 'stupid', 'whether', 'pleasure', 'making', 'daisy', 'chain', 'would', 'be', 'worth', 'trouble', 'getting', 'up', 'picking', 'daisies', 'when', 'suddenly', 'White', 'with', 'pink', 'eyes', 'ran', 'close', 'There', 'so', 'VERY', 'remarkable', 'that', 'nor', 'did', 'think', 'much', 'out', 'way', 'hear', 'say', 'itself', 'Oh', 'dear', 'shall', 'late', 'over', 'afterwards', 'occurred', 'ought', 'have', 'wondered', 'at', 'this', 'time', 'all', 'seemed', 'quite', 'natural', 'actually', 'TOOK', 'A', 'WATCH', 'OUT'

>**(b)** How many times does the word “the” appear? What about the word “The”?

In [53]:
# code here
alice_word['the']

1683

In [54]:
alice_word['The']

119

>**(d)** Modify the code so words are counted independent of whether they are made of upper or
lower case letters. i.e., “the”, “The” and “tHE” are all treated as the same word.


In [55]:
alice_word = {}
for line in preprocessed.split("\n"):
    for word in line.strip().split():
        word = word.lower()
        if word in alice_word.keys():
            alice_word[word] += 1
        else:
            alice_word[word] = 1
            
print(alice_word.keys())

dict_keys(['chapter', 'i', 'down', 'the', 'rabbit', 'hole', 'alice', 'was', 'beginning', 'to', 'get', 'very', 'tired', 'of', 'sitting', 'by', 'her', 'sister', 'on', 'bank', 'and', 'having', 'nothing', 'do', 'once', 'or', 'twice', 'she', 'had', 'peeped', 'into', 'book', 'reading', 'but', 'it', 'no', 'pictures', 'conversations', 'in', 'what', 'is', 'use', 'a', 'thought', 'without', 'so', 'considering', 'own', 'mind', 'as', 'well', 'could', 'for', 'hot', 'day', 'made', 'feel', 'sleepy', 'stupid', 'whether', 'pleasure', 'making', 'daisy', 'chain', 'would', 'be', 'worth', 'trouble', 'getting', 'up', 'picking', 'daisies', 'when', 'suddenly', 'white', 'with', 'pink', 'eyes', 'ran', 'close', 'there', 'remarkable', 'that', 'nor', 'did', 'think', 'much', 'out', 'way', 'hear', 'say', 'itself', 'oh', 'dear', 'shall', 'late', 'over', 'afterwards', 'occurred', 'ought', 'have', 'wondered', 'at', 'this', 'time', 'all', 'seemed', 'quite', 'natural', 'actually', 'took', 'watch', 'its', 'waistcoat', 'poc

In [56]:
alice_word['the']

1814

In [57]:
alice_word['The']

KeyError: 'The'

'the'의 카운트에 'The'의 카운트가 합쳐졌고, 딕셔너리에 'The'는 더이상 존재하지 않는다.

>**(e)** Repeat the previous exercise, but instead of counting the number of times a word appears,
count the number of times pairs of words appear. You might ﬁnd it useful to store the
previous word in a variable.

In [58]:
# code here
alice_word_pair = {}

pre_word = ""
for line in preprocessed.split():
    for word in line.strip().split():
        word = word.lower()
        word_pair = (pre_word, word)
        if word_pair in alice_word_pair.keys():
            alice_word_pair[word_pair] += 1
        elif pre_word == "":
            pass
        else:
            alice_word_pair[word_pair] = 1
        pre_word = word  

print(alice_word_pair)

{('chapter', 'i'): 1, ('i', 'down'): 1, ('down', 'the'): 11, ('the', 'rabbit'): 24, ('rabbit', 'hole'): 4, ('hole', 'alice'): 1, ('alice', 'was'): 17, ('was', 'beginning'): 5, ('beginning', 'to'): 7, ('to', 'get'): 18, ('get', 'very'): 1, ('very', 'tired'): 3, ('tired', 'of'): 5, ('of', 'sitting'): 1, ('sitting', 'by'): 1, ('by', 'her'): 2, ('her', 'sister'): 7, ('sister', 'on'): 1, ('on', 'the'): 37, ('the', 'bank'): 3, ('bank', 'and'): 1, ('and', 'of'): 1, ('of', 'having'): 2, ('having', 'nothing'): 1, ('nothing', 'to'): 3, ('to', 'do'): 20, ('do', 'once'): 1, ('once', 'or'): 3, ('or', 'twice'): 3, ('twice', 'she'): 1, ('she', 'had'): 60, ('had', 'peeped'): 1, ('peeped', 'into'): 1, ('into', 'the'): 24, ('the', 'book'): 2, ('book', 'her'): 1, ('sister', 'was'): 1, ('was', 'reading'): 2, ('reading', 'but'): 1, ('but', 'it'): 20, ('it', 'had'): 17, ('had', 'no'): 5, ('no', 'pictures'): 1, ('pictures', 'or'): 2, ('or', 'conversations'): 2, ('conversations', 'in'): 1, ('in', 'it'): 8, ('

>**(f)** What are the most common words and pairs of words in Alice in Wonderland?<br> You might find the *sorted* function or the *sort* function for lists to be useful.


In [59]:
# hint: example of how you use sorted
x = [1,4,2,7,5,6,3]
print(x)
print(sorted(x),type(sorted(x))) # outputs a list
import numpy as np
print(np.sort(x),type(np.sort(x)))  # outputs a numpy.ndarray

[1, 4, 2, 7, 5, 6, 3]
[1, 2, 3, 4, 5, 6, 7] <class 'list'>
[1 2 3 4 5 6 7] <class 'numpy.ndarray'>


In [60]:
import operator
sorted(alice_word.items(), key=operator.itemgetter(1), reverse = True)[0]

('the', 1814)

In [61]:
import operator
sorted(alice_word_pair.items(), key=operator.itemgetter(1), reverse = True)[0]

(('said', 'the'), 210)

### Problem 4. ArgMax and ArgSort

>**(a)** Finding the index of the largest (or smallest) element in a list is a commonly needed opera-
tion, but Python does not provide this function in its standard library (numpy will provide those). Write two functions


In [63]:
def argmax(list_input):
    tmp = list_input[0]
    for i, val in enumerate(list_input):
        if val > tmp:
            max_index = i
            tmp = val
    return max_index
def argmin(list_input):
    tmp = list_input[0]
    for i, val in enumerate(list_input):
        if val < tmp:
            min_index = i
            tmp = val
    return min_index

>that return the index of the largest and smallest element in the list *list_input* respectively. Example output:


    >>> list1 = [1,3,2,6,0,2,3,4,5]
    >>> argmax(list1)
    3
    >>> argmin(list1)
    4

In [64]:
# try it here
list1 = [1,3,2,6,0,2,3,4,5]
argmax(list1)

3

In [65]:
argmin(list1)

4

>**(b)** **(extra)** Instead of just finding the index of the largest or smallest element, one might be interested in the entire list of indices that would sort the list. In one of the previous exercises we presented you with this piece of code for finding the indices that sort a list.


In [66]:
l = [1,3,2,6,0,2,3,4,5]
list(zip(*sorted(zip(l, range(len(l))))))[1]

(4, 0, 2, 5, 1, 6, 7, 8, 3)

In [67]:
list(zip(l, range(len(l))))

[(1, 0), (3, 1), (2, 2), (6, 3), (0, 4), (2, 5), (3, 6), (4, 7), (5, 8)]

In [68]:
sorted(zip(l, range(len(l))))

[(0, 4), (1, 0), (2, 2), (2, 5), (3, 1), (3, 6), (4, 7), (5, 8), (6, 3)]

>It works by combining the list with the list of indices, sorting the combined list, and then untangling the results. Have a look at the documentation of the *zip* function to understand how it works. Write a function:

In [69]:
def argsort(l):
    # your code here
    index_and_value = []
    sorted_index = []
    for i, val in enumerate(l):
        index_and_value.append((val, i))
    for a, b in sorted(index_and_value):
        sorted_index.append(b)
    return sorted_index

l = [1,3,2,6,0,2,3,4,5]
argsort(l)

[4, 0, 2, 5, 1, 6, 7, 8, 3]

>that returns the list of indices that would sort the list, but instead of using the hard to read
line above that uses zip, use list comprehensions. Example output:

    >>> l = [1,3,2,6,0,2,3,4,5]
    >>> argsort(l)
    [4, 0, 2, 5, 1, 6, 7, 8, 3]
    >>> [l[i] for i in argsort(l)]
    [0, 1, 2, 2, 3, 3, 4, 5, 6]


In [70]:
# try it here
l = [1,3,2,6,0,2,3,4,5]
print(argsort(l))
print([l[i] for i in argsort(l)])

[4, 0, 2, 5, 1, 6, 7, 8, 3]
[0, 1, 2, 2, 3, 3, 4, 5, 6]


### Problem 5. Simple ciphers


Suppose you wish to send your friend a message, and if someone happens to look at it, you do not want them to know what it says.<br>
A simple way of doing this is to replace each letter, with
a different one.<br>
For example, suppose I wish to send the phrase “dancing is silent poetry”.<br>
By exchanging each letter with another, we can encode this as: “robqwbu wg gwzsbh dcshfm”.

>**(a)** Write a function that swaps the letter in a string according to a dictionary. For example:


In [71]:
def swapdict(string, dic):
    # your code here
    print_output = ""
    for letter in string:
        if letter in dic.keys():
            print_output += dic[letter]
        else:
            print_output += letter
    return print_output

    >>> print swapdict('hello', {'e': 'i'})
    hillo
    >>> print swapdict('hello', {'l': 'w'})
    hewwo
    >>> print swapdict('hello', {'l': 'm', 'h': 'p', 'e': 'o', 'o': 'e'})
    pomme

In [72]:
# your code here
print(swapdict('hello', {'e': 'i'}))

hillo


In [73]:
print(swapdict('hello', {'l': 'm', 'h': 'p', 'e': 'o', 'o': 'e'}))

pomme


>**(b)** Write a function that generates a dictionary whose keys are letters of the alphabet, and whose values are those letters shifted along by a given number of letters.


In [74]:
def shiftdict(i):
    # your code here
    import string
    alphabet = string.ascii_lowercase
    dic = {}
    for letter in alphabet:
        if (ord(letter)+i) > ord('z'):
            dic[letter] = chr(ord(letter) + i - ord('z') + ord('a') - 1)
        elif (ord(letter)+i) < ord('a'):
            dic[letter] = chr(ord(letter) + i + ord('z') - ord('a') + 1)
        else:
            dic[letter] = chr(ord(letter) + i)
    return dic

shiftdict(13)

{'a': 'n',
 'b': 'o',
 'c': 'p',
 'd': 'q',
 'e': 'r',
 'f': 's',
 'g': 't',
 'h': 'u',
 'i': 'v',
 'j': 'w',
 'k': 'x',
 'l': 'y',
 'm': 'z',
 'n': 'a',
 'o': 'b',
 'p': 'c',
 'q': 'd',
 'r': 'e',
 's': 'f',
 't': 'g',
 'u': 'h',
 'v': 'i',
 'w': 'j',
 'x': 'k',
 'y': 'l',
 'z': 'm'}

    >>> print shiftdict(0)
    {'a': 'a', 'b': 'b', ..., 'z': 'z'}
    >>> print shiftdict(3)
    {'a': 'd', 'b': 'e', ..., 'z': 'c'}
    >>> print shiftdict(13)
    {'a': 'n', 'b': 'o', ..., 'z': 'm'}

>In the first case, the letters are not shifted, because the argument to *shiftdict* is zero. In the second case, letters are shifted along by three letters: “a” is the first letter, and “d” is the forth letter, and so key “a” points to letter “d”.

In [75]:
# try it here
print(shiftdict(3))

{'a': 'd', 'b': 'e', 'c': 'f', 'd': 'g', 'e': 'h', 'f': 'i', 'g': 'j', 'h': 'k', 'i': 'l', 'j': 'm', 'k': 'n', 'l': 'o', 'm': 'p', 'n': 'q', 'o': 'r', 'p': 's', 'q': 't', 'r': 'u', 's': 'v', 't': 'w', 'u': 'x', 'v': 'y', 'w': 'z', 'x': 'a', 'y': 'b', 'z': 'c'}


>**(c)** Now we are ready to encode our message: “dancing is silent poetry”.


    >>> print swapdict('dancing is silent poetry', shiftdict(14))

In [76]:
# your code here
print(swapdict('dancing is silent poetry', shiftdict(14)))

robqwbu wg gwzsbh dcshfm


>Check that it matches the encoding given above.


>**(d)** Write a function that takes a dictionary and swaps the roles of the keys and the values.


In [77]:
def invertdict(dictionary):
    # your code here
    new_dic = {}
    for k, v in dictionary.items():
        new_dic[v] = k
    return new_dic

Here are some examples to check it works:

    >>> invertdict({'a':'b'})
    {'b': 'a'}
    >>> invertdict({'b':'a', 'a': 'b'})
    {'a': 'b', 'b': 'a'}
    >>> invertdict({'a':'b', 'b': 'c', 'c': 'a'})
    {'a': 'c', 'b': 'a','c': 'b'}

In [78]:
# your code here
print(invertdict({'a':'b'}))
print(invertdict({'b':'a', 'a': 'b'}))
print(invertdict({'a':'b', 'b': 'c', 'c': 'a'}))

{'b': 'a'}
{'a': 'b', 'b': 'a'}
{'b': 'a', 'c': 'b', 'a': 'c'}


>**(e)** Can you decode this message, that was encoded using the same scheme? “qzuipo nblft ju tjnqmf ipqfgvmmz”. Use only *invertdict*, *swapdict* and *shiftdict*.


In [79]:
# your code here
swapdict('qzuipo nblft ju tjnqmf ipqfgvmmz', invertdict(shiftdict(1)))

'python makes it simple hopefully'

>**(f)** You notice that your friend is sending encrypted messages to other people, but they appear to be encoded using a different argument to shiftdict.<br>
Use a for-loop, swapdict and shiftdict to work out the encoding scheme, and what this message says: “nyhcpaf pz aol yvva vm spnoaulzz”.


In [80]:
# your code here
for i in range(27):
    print(swapdict('nyhcpaf pz aol yvva vm spnoaulzz', invertdict(shiftdict(i))))

nyhcpaf pz aol yvva vm spnoaulzz
mxgboze oy znk xuuz ul romnztkyy
lwfanyd nx ymj wtty tk qnlmysjxx
kvezmxc mw xli vssx sj pmklxriww
judylwb lv wkh urrw ri oljkwqhvv
itcxkva ku vjg tqqv qh nkijvpguu
hsbwjuz jt uif sppu pg mjhiuoftt
gravity is the root of lightness
fqzuhsx hr sgd qnns ne khfgsmdrr
epytgrw gq rfc pmmr md jgefrlcqq
doxsfqv fp qeb ollq lc ifdeqkbpp
cnwrepu eo pda nkkp kb hecdpjaoo
bmvqdot dn ocz mjjo ja gdbcoiznn
alupcns cm nby liin iz fcabnhymm
zktobmr bl max khhm hy ebzamgxll
yjsnalq ak lzw jggl gx dayzlfwkk
xirmzkp zj kyv iffk fw czxykevjj
whqlyjo yi jxu heej ev bywxjduii
vgpkxin xh iwt gddi du axvwicthh
ufojwhm wg hvs fcch ct zwuvhbsgg
tenivgl vf gur ebbg bs yvtugarff
sdmhufk ue ftq daaf ar xustfzqee
rclgtej td esp czze zq wtrseypdd
qbkfsdi sc dro byyd yp vsqrdxocc
pajerch rb cqn axxc xo urpqcwnbb
ozidqbg qa bpm zwwb wn tqopbvmaa
nyhcpaf pz aol yvva vm spnoaulzz


gravity is the root of lightness